version: '3'
services:
  node-app:
    build:
      context: ./app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Arabica@1A
      MYSQL_DATABASE: nodejs_db
      MYSQL_USER: apeksha
      MYSQL_PASSWORD: Robusta@1A

  data-container:
    image: busybox:latest
    volumes:
      - ./app:/app
      - db_data:/var/lib/mysql   

volumes:
  db_data:       
